apiVersion: v1
kind: ServiceAccount
metadata:
  name: package-deployer
  namespace: default
  imagePullSecrets: dockerhubregkey
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: package-deployer-role
  namespace: default
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: package-deployer-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: package-deployer
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: package-deployer-role